### ISSUE TITLE
Enrich error for "Getting started with ES|QL" notebook

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#207] opened 2024-03-18 03:56 UTC
For EQSL getting started notboook at https://github.com/elastic/elasticsearch-labs/blob/main/notebooks/esql/esql-getting-started.ipynb. The problem lies here in the following piece of code:

```
# Define the enrich policy
policy = {
    "match": {
        "indices": "clientips",
        "match_field": "client_ip",
        "enrich_fields": ["env"],
    }
}

# Put the enrich policy
client.enrich.put_policy(name="clientip_policy", body=policy)

# Execute the enrich policy without waiting for completion
client.enrich.execute_policy(name="clientip_policy", wait_for_completion=False)
```

The policy is executed in asynchronous way, and run the following code immediately, it results error:

```
esql_query = """
FROM sample_data
| KEEP @timestamp, client_ip, event_duration
| EVAL client_ip = TO_STRING(client_ip)
| ENRICH clientip_policy ON client_ip WITH env
"""
response = client.esql.query(query=esql_query)
format_response(response)
```

I think the enrich index is not ready. To correct the problem, we need to make the call to synchronous:

`client.enrich.execute_policy(name="clientip_policy", wait_for_completion=True)`
     

<img width="1268" alt="image" src="https://github.com/elastic/elasticsearch-labs/assets/8455957/e2a4703e-17e1-4e8d-9874-4e4b5f4e5c00">

**Comment by serenachou** [comment] 2024-03-26 22:26
@leemthompo assigning to you as the original author

**Comment by leemthompo** [comment] 2024-03-27 09:10
@liu-xiao-guo thanks for flagging! Interestingly, we didn't run into this problem testing against an 8.13.0 cloud instance, but we did some hit issues running locally which we determined was indeed due to enrich. Did you also test against 8.13.0? 

But your point makes total sense to me and I'm surprised this was set to `False`.

**Comment by leemthompo** [comment] 2024-03-27 11:05
I reproduced error, fix is in ☝️

**Closed** 2024-03-27 11:54 UTC
